server:
  port: 9002

#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/bit701?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://db-g6764-kr.vpc-pub-cdb.ntruss.com:3306/bit701?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://db-g66k8-kr.vpc-pub-cdb.ntruss.com:3306/bit701?serverTimezone=Asia/Seoul
    url: jdbc:mysql://db-h04kp-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bit123!@#
  servlet:
    multipart:
      max-file-size:
        20MB


#mybatis
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
    - /mapper/**/*.xml